[package]
name = "gitlab-alfred-workflow"
version = "0.0.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
powerpack = "0.3.0"
